// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqbbXAsLTFi_KEiFl4Qh1I0ijpZREiREk',
    appId: '1:978185233537:web:a15809cff541d9ac295980',
    messagingSenderId: '978185233537',
    projectId: 'flutter-food-store-e31ac',
    authDomain: 'flutter-food-store-e31ac.firebaseapp.com',
    storageBucket: 'flutter-food-store-e31ac.appspot.com',
    measurementId: 'G-EZX83KWZMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkHCvx-NRHthONneeQ7-93W1qtNFnhOag',
    appId: '1:978185233537:android:c7d23ca44766f874295980',
    messagingSenderId: '978185233537',
    projectId: 'flutter-food-store-e31ac',
    storageBucket: 'flutter-food-store-e31ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORKWCITMm_MAs7FiFeob5QH6uudHJr2w',
    appId: '1:978185233537:ios:06139464a5afab3b295980',
    messagingSenderId: '978185233537',
    projectId: 'flutter-food-store-e31ac',
    storageBucket: 'flutter-food-store-e31ac.appspot.com',
    iosBundleId: 'com.example.flutterFoodFirebasePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORKWCITMm_MAs7FiFeob5QH6uudHJr2w',
    appId: '1:978185233537:ios:06139464a5afab3b295980',
    messagingSenderId: '978185233537',
    projectId: 'flutter-food-store-e31ac',
    storageBucket: 'flutter-food-store-e31ac.appspot.com',
    iosBundleId: 'com.example.flutterFoodFirebasePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqbbXAsLTFi_KEiFl4Qh1I0ijpZREiREk',
    appId: '1:978185233537:web:6acb3d3d61c47969295980',
    messagingSenderId: '978185233537',
    projectId: 'flutter-food-store-e31ac',
    authDomain: 'flutter-food-store-e31ac.firebaseapp.com',
    storageBucket: 'flutter-food-store-e31ac.appspot.com',
    measurementId: 'G-VZH5SRNR3T',
  );

}